### ISSUE TITLE
Restructure for els-article template

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#81]
I suggest Ren. and Sust. energy reviews..

Todo's: 

* [x] Check length of abstract and paper in general  (number of words)
* [ ] Fix literature format #83 
* [ ] Check literature again (title etc) #83 
* [x] Fix tables #84 
* [x] Fix Headings (enumeration) and References inside text (replace nameref) 
* [ ] Make sure all packages are included in the manuscript if they are special and not incl. in texlive
* [x] Fix title page, title, affiliation, journal title etc.
* [ ] General overall check of the document
* [x] Figure out the correct bst-file for selected journal and push it to repository @simnh
* [ ] Rewrite first paragraph of abstract #82 

Please add todos here if you find anything...

**Comment by ckaldemeyer** [comment]
Before we start I would really check https://github.com/simnh/addressing_challenges_oemof/issues/10 again. I am absolutely o.k. with Ren. and Sust. energy reviews but there are already very similar recent publications in IEEE which are also useable as a reference to distinguish ourselves, etc. which might make it easier to get accepted..

**Comment by ckaldemeyer** [comment]
**Hier nochmal Simons Mail, damit nicht alles in den Mails verloren geht ;-):**

Ok, also da Cord nun noch ein paar Vorschläge germacht hat müssen wir nochmal gucken, aber ich habe schonmal ein Issue angelegt, dass general für alle Journals todos enthält...bevor man sie abarbeitet, sollten wir uns natürlich entschieden haben. Ich habe jetzt mal auf dem master die umstrukturierung für ein els-art. gemacht.

https://github.com/simnh/addressing_challenges_oemof/issues/81

Zu Cords Vorschlägen: Da würde meiner Meinung nach nur AIP passen, IEEE fände ich aufgrund des Aufhängers nicht wirklich geeignet, es sei denn, wir schmeißen alles raus und nehmen nur den oemof beschreibenden teil...

Ich denke vom Scope her würde das ganz gut passen:

https://www.journals.elsevier.com/renewable-and-sustainable-energy-reviews/

allerdinsg sicherlich auch nicht ganz einfach reinzukommen vermutlich. Immer sollten wir die Länge berücksichtigen, da unser doch recht lang ist (hoffentlich unter 10.000 W), das war bei plos kein problem, aber bei anderen schon...

Sollten aber bald entscheiden, dann umformatieren und einreichen....gener nochmal lesen, wir haben jetzt ja etwas abstand ;).  Vor Freitag komme ich nich dazu etwas zu machen, aber bis dahin hätte ich gerne eine Entscheidung. Mein Vorschlag kennt ihr ja nun...

Das fände ich auch noch eine Überlegung wird, ist möglicherweise nicht gazn so mafia mäßig wie elsevier...aber ist mir auch egal jetzt :)

Energy, Sustainability and Society (Springer)

**Comment by ckaldemeyer** [comment]
> Zu Cords Vorschlägen: Da würde meiner Meinung nach nur AIP passen, IEEE fände ich aufgrund des Aufhängers nicht wirklich geeignet, es sei denn, wir schmeißen alles raus und nehmen nur den oemof beschreibenden teil...
> 
> Ich denke vom Scope her würde das ganz gut passen:
> 
> https://www.journals.elsevier.com/renewable-and-sustainable-energy-reviews/
> 
> allerdinsg sicherlich auch nicht ganz einfach reinzukommen vermutlich. Immer sollten wir die Länge berücksichtigen, da unser doch recht lang ist (hoffentlich unter 10.000 W), das war bei plos kein problem, aber bei anderen schon...

Nochmal ganz anders gedacht: Könnte man das Paper nicht auch in zwei Papern denken?

Also:

1. Paper: Reine Vorstellung von oemof
2. Paper: Adressing.... mit Bezug auf das erste Paper

Die Inhalte sind ja da und so hätte man die sperrige Worthürde umgangen..

**Comment by ckaldemeyer** [comment]
Ich könnte mir vorstellen, dass das so auch schneller durchginge..

**Comment by simnh** [comment]
Ich hatte auch schon die idee, dann könnte man einfach bei IEEE oemof machen und addressing challenges wo anders, aber ich denke wir sollten den Aufwand dafür nicht unterschätzen, da ja doch nochmal extra Intro, Conclusion etc. notwendig wäre....aber charmant finde ich es schon...und eigentlich ist es ja auch one paper one message...daher wäre das vielleicht gar nicht schlecht!

Eigentlich wäre es ohnehin gut erst die Methodik für die Modell bewertung und dann eine Berwertung von verschiedenen...aber man könnte da ja als beispiel oemof nehmen, dann ließe sich die methodik noch weiterentwicklen so auch mit so dingen wie  model fact sheets verheiraten (ganz viel später)

**Comment by simnh** [comment]
Ok, hat hier irgendwer eine Meinung?

**Comment by fraukewiese** [comment]
Ich hab da nicht so richtig ne Meinung zu außer den Auwand so gering wie möglich zu halten. Lass uns nur in dem Falle zwei Paper draus machen, falls ein Reviewer das vorschlägt oder kein präferiertes Journal ein so langes Paper akzeptiert (glaub ich aber nicht).
Bei der Anpassung des jetzigen Papers an ein anderes Journal-Format kann ich mithelfen. Wär ja praktisch wenn das Format nicht so unterschiedlich ist. Lass uns den Anspruch nicht so hochsetzen, jetzt nochmal viel umzumodeln - es ist so wie es ist ganz schön gut - da es so schade um die Mühe ist wenn es dann an einem einfach nur blöden Reviewer scheitert (was ja manchmal passiert).
danke für Eure Vorschläge soweit.
Ach ja und dass wir open source publizieren wäre ja schon gut - obwohl das mit dem preprint veröffentlichen ja eigentlich auch schon ne super Option ist.
Frauke

**Comment by simnh** [comment]
Danke Frauke! 

Finde ich nen soliden Vorschlag. Ich habe auch nochmal drüber geguckt und denke der Aufwand für 2 draus machen nicht zu unterschätzen. 

Also open access ist für mich auch klar, nur die Frage ist halt ob bei den Verbrechern oder bei den Guten ;).  

Ich schlage aber vor einfach in dem jetzigen Format zu arbeiten, bei elsevier stehen uns dann verschiedene Optionen zu verfügung...

Es sei den irgendjemand schreit: Springer! (Denn die anderen sehe ich nicht als geeignet an, außer API, aber wenn Cord schon sagt das es schwierig ist würde ich jetzt mal mit elsevier gehen...

**Comment by ckaldemeyer** [comment]
> Danke Frauke!
> 
> Finde ich nen soliden Vorschlag. Ich habe auch nochmal drüber geguckt und denke der Aufwand für 2 draus machen nicht zu unterschätzen.
> 
> Also open access ist für mich auch klar, nur die Frage ist halt ob bei den Verbrechern oder bei den Guten ;).
> 
> Ich schlage aber vor einfach in dem jetzigen Format zu arbeiten, bei elsevier stehen uns dann verschiedene Optionen zu verfügung...
> 
> Es sei den irgendjemand schreit: Springer! (Denn die anderen sehe ich nicht als geeignet an, außer API, aber wenn Cord schon sagt das es schwierig ist würde ich jetzt mal mit elsevier gehen...

Danke für eure Vorschläge. Ich würde da voll mitgehen :+1:

**Comment by ckaldemeyer** [comment]
Das mit den zwei Papern ist glaube ich ne gute Idee aber wir haben ja aus der Vergangenheit gelernt, dass man den Aufwand oftmals unterschätzt. Somit finde ich die Idee wenig Aufwand zu betreiben gerade sehr gut :smile:

**Comment by fraukewiese** [comment]
Daumen hoch, ich schrei nix sondern nicke zustimmend :)

**Comment by gplssm** [comment]
Danke für eure bisherigen Überlegungen! Ich gehe da voll mit. Zwei Fragen bleiben mir noch bevor wir die Anpassungsarbeit an das Format von _Ren. and Sust. energy reviews_ angehen:
1. Gibt das Journal eine max. Länge vor und ist unser Artikel im gegenwärtigen Zustand innerhalb des Limits?
2. Meines Wissens kostet OA be Elsevier 2500$. Stünden diese auch zur Verfügung?

Wenn das passt, go for it und ich helfe natürlich die TODOs zu erledigen. Lass uns dazu doch in der obigen checkbox liste einfach die Zuständigkeiten dran schreiben.

**Comment by simnh** [comment]
Meines Wissens nicht, zumindest steht nicht im Guide for authors. Das gesamte dokument ist 13000 Wörter (inkl. quellen und abstract acknoledgments etc). Bei energy policy ist ein review max 10.000. 
Also denke ich selbst wenn sollten wir nicht wesentlich über 10000 kommen. 

Geld kriegen wir denke ich hin...sonst bezahlt olav das

**Comment by ckaldemeyer** [comment]
"The open access publication fee for this journal is USD 3300, excluding taxes. Learn more about Elsevier's pricing policy: http://www.elsevier.com/openaccesspricing."

https://www.elsevier.com/journals/renewable-and-sustainable-energy-reviews/1364-0321/guide-for-authors#13300

Eine Teilsumme (1750 EUR meine ich) hatten wir ja schon beantragt.

Bei max. 10.000 Wörtern und derzeit 13.000 Wörtern finde ich es schwierig zu kürzen. Evtl. könnte man da doch besser die 2 Paper Variante ins Spiel bringen..

**Comment by ckaldemeyer** [comment]
Übrigens finde ich USD 3300 echt unverschämt. Eigentlich sollte man so einen Dreck nicht unterstützen..

**Comment by simnh** [comment]
> Bei max. 10.000 Wörtern und derzeit 13.000 Wörtern finde ich es schwierig zu kürzen. Evtl. könnte man da doch besser die 2 Paper Variante ins Spiel bringen..

wie gesagt ohne quellen etc...die sind gerade schon ~ 3000 Wörter im aktuellen pdf durch die elsartc-bst daher ist der Artikel tatsächlich ziemlich genau ~ 10.000

**Comment by gplssm** [comment]
Ich habe mal mit Kile gezählt
![addressing_paper_word_count](https://cloud.githubusercontent.com/assets/8255114/24827918/5206a838-1c53-11e7-9b14-3bbade2017be.png)

Wir sind also 319 Wörter über der 10.000er Marke.

**Comment by simnh** [comment]
Aber wie gesagt, es gibt keine Beschränkung und außerdem werden die Quellen noch deutlich kürzer.
Ich habe schon mal mit dem Titleblatt angefangen. 

Könnt ihr euch einfach selbst sachen aussuchen und ein Issue dazu anlegen?

**Comment by simnh** [comment]
here are info for building the manuscript (reminder for me) 

https://www.elsevier.com/authors/author-schemas/latex-instructions
