### ISSUE TITLE
Feedback Guido

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#90]
Ich habe den Artikel nochmal hinsichtlich Konsistenz gelesen. Auf dem Weg sind mir gleich ein paar Sachen aufgefallen, die ich entweder direkt umsetze oder eine mögliche Aufgabe definiert habe (s. unten). Meine Idee wäre jetzt, dass wir uns je Aufgabe unten abstimmen, ob und wie wir die abarbeiten wollen und sich dann jemand findet, der/die das macht. Schreibt einfach eure Meinung ins jeweilige Issue (oder nutzt Emoticons). Lasst euch von der Liste nicht abschrecken. So übel ist der Artikel nicht, aber wir könnten es dem Leser noch einfacher machen.

Die möglichen Überarbeitungsaufgaben nach subjektiver Priorität

- [x] Diverse kleine Änderungen/Fehlerkorrekturen einpflegen [macht Guido im Master]
- [x] Artikelübersicht in Introduction #91
- [ ] Methodik mit Literatur belegen #92
- [ ] Struktur der Diskussion in Kap. 4 #93
- [ ] Arguments-Ascpects-Relationships Grafik #94 
- [x] Verwendung Begriff "aspects" #95
- [x] Verwendung Begriff _arguments_ #96
- [ ] Überarbeitung Absatz zu Einführung oemof #97
- [x] Argumente vor Verwendung in 4.1 ff. einmal nennen (teilweise der Fall)
- [ ] Die Darstellung adressierter Aspekte (Challenges) positiver und mutiger präsentieren
- [ ] Überarbeitung Sprache/Ausdruck an einigen Stellen
- [ ] Verwendung von network oder (bipartite) graph vereinheitlichen
- [ ] Abstract überarbeiten
- [ ] Naming glatt ziehen: Characteristic -> Property, Argument -> Characteristic

**Comment by simnh** [comment]
Danke guido! Ich denke alle Änderungen machen Sinn und sollte vor einreichung umgesetzt werden. Ich werde mir nach und nach einige Punkte rauspicken und vorher hier bzw. in dem jeweiligen Issue bescheid geben.

**Comment by fraukewiese** [comment]
Hallo @simnh @gplssm @ckaldemeyer , 
habe nen Teil gemacht und das was Einzelissues hat kommentiert. Zu den anderen von Guido genannten tasks:
- änderungen einpflegen (macht Guido im Master) - wann machst Du das @gplssm oder ist das shcon erledigt?
- Addressierte aspecte positiver formulieren: Ich finde es klingt wie es ist gut beschrieben. Wir müssen uns ja nicht der allgemein verbreiteten "wir sind die geilsten" Prahlerei anschließen
- Überarbeitung Sprache Ausdruck, da sind wir inzwischen denke ich an einem Level angekommen wo es Geschmacksfragen sind, ich selbst finde da nichts mehr essentielles und es muss ja kein Gedicht werden
- letzen Punkt versteh ich nicht

Einreiche-Deadline? Denke das meiste von Guidos andern Punkten sind nice-to-haves, wer will da noch was umsetzen und bis wann? Falls keine Zeit dafür ist würde ich es eher lassen.

**Comment by ckaldemeyer** [comment]
https://github.com/simnh/addressing_challenges_oemof/pull/98

**Comment by gplssm** [comment]
Liebe Leute,

es tut mir Leid, dass von mir so wenig Rückmeldung kam. Grad komme ich nicht allem nach... Zudem düse ich heute Abend in den Urlaub und bin erst am 19.6. wieder verfügbar. Deshalb hab ich schnell noch meine kleinen Änderungen gepusht. Allerdings musste ich einige Punkte, die ich mir noch auf dem PDF markiert hatte liegen lassen, weil sie zuviel Zeit kosteten. Wenn ihr das Paper bis zu meiner Rückkehr noch nicht eingereicht habt, würde ich diese übrigen Änderungen gerne noch einbringen.
Schaut mal was ihr aus den restlichen Issues so macht. Vielen Dank auf jeden Fall, dass ihr meine Vorschläge überhaupt aufgegriffen habt! :)

Ahoi, ich bin dann weg...

**Comment by ckaldemeyer** [comment]
> Liebe Leute,
> 
> es tut mir Leid, dass von mir so wenig Rückmeldung kam. Grad komme ich nicht allem nach... Zudem düse ich heute Abend in den Urlaub und bin erst am 19.6. wieder verfügbar. Deshalb hab ich schnell noch meine kleinen Änderungen gepusht. Allerdings musste ich einige Punkte, die ich mir noch auf dem PDF markiert hatte liegen lassen, weil sie zuviel Zeit kosteten. Wenn ihr das Paper bis zu meiner Rückkehr noch nicht eingereicht habt, würde ich diese übrigen Änderungen gerne noch einbringen.
> Schaut mal was ihr aus den restlichen Issues so macht. Vielen Dank auf jeden Fall, dass ihr meine Vorschläge überhaupt aufgegriffen habt! :)
> 
> Ahoi, ich bin dann weg...

Danke, Guido. Ich warte jetzt erstmal auf das Feedback zu meinem PR. Wenn das für euch o.k. ist, würde ich die Mergekonflikte beheben und zurückmergen in den Master. So lange mache ich aber erstmal etwas anderes..

**Comment by simnh** [comment]
meinetmegen kannst du gerne pushen...ich weiß aber nicht ob wir noch ne discussion brauchen? bzw ob wir das nicht in eine section discussion and conclusion zusammenfassen

**Comment by ckaldemeyer** [comment]
> meinetmegen kannst du gerne pushen...ich weiß aber nicht ob wir noch ne discussion brauchen? bzw ob wir das nicht in eine section discussion and conclusion zusammenfassen

Da war ich mir auch noch unklar und hatte in die gleiche Richtung gedacht. O.k., dann merge ich das mal..
